package model;

public enum ErrorType {

    SUCCESS,

    NULL_INPUT,
    EMPTY_INPUT,

    ALPHABETIC_CHARACTERS,
    INVALID_SPECIAL_CHARACTERS,
    INVALID_SIGN,
    MULTIPLE_DECIMAL_POINTS,
    DECIMAL_NOT_ALLOWED,

    INTEGER_OVERFLOW,
    LONG_OVERFLOW,
    DOUBLE_OVERFLOW
}